spring:
  cloud:
    aws:
      region:
        static: us-east-1
  application:
    name: hackathon

aws:
  region: ${AWS_REGION:us-east-1}
  accessKey: ${AWS_ACCESS_KEY_ID:}
  secretKey: ${AWS_SECRET_ACCESS_KEY:}

server:
  port: 8000

management:
  endpoints:
    web:
      exposure:
        include: health


sqs:
  queue: sqs-processamento

bucket:
  name: bucket-hackathon-fiap-raw-videos
  destination:
    path: C:/Users/Public/fiap_videos