spring:
  application:
    name: hackathon

server:
  port: 8000

management:
  endpoints:
    web:
      exposure:
        include: health

aws:
  region: us-east-1
  sqs:
    queue: sqs-processamento
  bucket:
    name: bucket-hackathon-fiap-raw-videos
    destination:
      path: /tmp