name: 'Deploy infra'

on:
  push:
    branches:
      - main
  workflow_dispatch:

env:
  IMAGE_NAME: hackathon-fiap-processamento-video
  AWS_REGION: us-east-1

jobs:
  push-to-registry:
    name: Push Docker Image
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Log in to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Extract metadata (tags, labels) for Docker
        id: meta
        uses: docker/metadata-action@v4
        with:
          images: ${{ secrets.DOCKER_USERNAME }}/${{ env.IMAGE_NAME }}

      - name: Build and push Docker image
        uses: docker/build-push-action@v3
        with:
          context: .
          push: true
          tags: |
            ${{ steps.meta.outputs.tags }}
            ${{ secrets.DOCKER_USERNAME }}/${{ env.IMAGE_NAME }}:${{ github.sha }}
          labels: ${{ steps.meta.outputs.labels }}
          build-args: |
            SPRING_PROFILES_ACTIVE=ci
            AWS_REGION=${{ env.AWS_REGION }}
            AWS_ACCESS_KEY_ID=${{ secrets.AWS_ACCESS_KEY_ID }}
            AWS_SECRET_ACCESS_KEY=${{ secrets.AWS_SECRET_ACCESS_KEY }}

  deploy-infra:
    needs: push-to-registry
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v3
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-session-token: ${{ secrets.AWS_SESSION_TOKEN }}
          aws-region: ${{ env.AWS_REGION }}

      - name: Set up Terraform
        uses: hashicorp/setup-terraform@v2
        with:
          terraform_version: 1.6.1

      - name: Initialize Terraform
        run: terraform init
        working-directory: './infra/'

      - name: Validate Terraform configuration
        run: terraform validate
        working-directory: './infra/'

      - name: Plan Terraform changes
        run: terraform plan -var="image_tag=${{ github.sha }}"
        working-directory: './infra/'

      - name: Apply Terraform changes
        run: terraform apply -auto-approve -var="image_tag=${{ github.sha }}"
        working-directory: './infra/'
